version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.21
    restart: always
    depends_on:
      - postgres
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
            migrations: true
  postgres:
    image: postgres:10.5
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - /Users/ssanchezt/Code/Docker/Databases/Postgres/Data:/var/lib/postgresql/data